name: 店铺关注有礼

on:
    # push:
    #     branches:
    #         - main
    schedule:
        - cron: "15 7 * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【店铺关注有礼】"
              run: |
                  node Ponysitters_Club_Season.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  SYNCURL: /The.Flash/The.Flash/monk_shop_follow_sku.js
                  SCKEY: ${{ secrets.SCKEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  EFORK: ${{ secrets.EFORK }}
                  GITHUB: ${{ secrets.GITHUB }}
